// A research agent that hires Veritas over CAP to fact-check before answering.

import { VeritasClient } from "@veritas/sdk/client.js";
import { capHire } from "@veritas/sdk/a2a/cap-hire.js";
import type { HireResult, VerificationReport } from "@veritas/sdk";

/** A single research question to investigate. */
interface ResearchQuery {
  readonly topic: string;
  /** Draft answer generated by the agent that needs fact-checking. */
  readonly draftAnswer: string;
}

/** Result of the agent's research + verification pass. */
interface ResearchResult {
  readonly topic: string;
  readonly draftAnswer: string;
  readonly verificationReport: VerificationReport | null;
  readonly trustScore: number;
  readonly finalAnswer: string;
}

/** Minimal agent config loaded from the environment. */
interface AgentConfig {
  readonly veritasApiBase: string;
  readonly veritasApiKey: string;
  readonly veritasServiceId: string;
  readonly buyerAddress: string;
  readonly amountUsdc: string;
  readonly timeoutMs: number;
}

function loadAgentConfig(): AgentConfig {
  const get = (key: string, fallback?: string): string => {
    const v = process.env[key] ?? fallback;
    if (v === undefined) throw new Error(`Missing required env var: ${key}`);
    return v;
  };

  return {
    veritasApiBase: get("VERITAS_API_BASE", "https://api.veritas.croo.app"),
    veritasApiKey: get("VERITAS_API_KEY"),
    veritasServiceId: get("VERITAS_SERVICE_ID", "veritas-standard"),
    buyerAddress: get("BUYER_WALLET_ADDRESS"),
    amountUsdc: get("HIRE_AMOUNT_USDC", "500000"),
    timeoutMs: parseInt(get("HIRE_TIMEOUT_MS", "180000"), 10),
  };
}

/** Summarise the report into a human-readable trust adjudication. */
function buildFinalAnswer(
  draftAnswer: string,
  report: VerificationReport | null,
): { score: number; answer: string } {
  if (!report) {
    return {
      score: 0,
      answer: `${draftAnswer}\n\n⚠️  Unable to verify — no report returned by Veritas.`,
    };
  }

  const score = report.trustScore / 100;
  const verdictLine = `Veritas trust score: **${report.trustScore}/100** (${(score * 100).toFixed(1)}%)`;

  const corrections = report.claims
    .filter((c) => c.verdict === "REFUTED" || c.verdict === "UNVERIFIABLE")
    .map((c) => `- "${c.claim.slice(0, 100)}": ${c.verdict}`)
    .join("\n");

  const correctionBlock =
    corrections.length > 0
      ? `\n\nClaims flagged:\n${corrections}`
      : "\n\nAll claims passed fact-checking.";

  return {
    score,
    answer: `${draftAnswer}\n\n---\n${verdictLine}${correctionBlock}\n\nSummary: ${report.summary}`,
  };
}

/** Hire Veritas to fact-check a draft answer before the agent publishes it. */
async function factCheckDraft(
  client: VeritasClient,
  cfg: AgentConfig,
  query: ResearchQuery,
): Promise<ResearchResult> {
  console.log(`\n[agent] Fact-checking draft for topic: "${query.topic}"`);

  let hireResult: HireResult;
  try {
    hireResult = await capHire(client.transport, {
      serviceId: cfg.veritasServiceId,
      claim: query.draftAnswer,
      amountUsdc: cfg.amountUsdc,
      buyerAddress: cfg.buyerAddress,
      metadata: { topic: query.topic, source: "a2a-research-agent" },
      completion: {
        pollIntervalMs: 3000,
        timeoutMs: cfg.timeoutMs,
        onPoll: (order: import("@veritas/sdk").Order) => {
          process.stdout.write(`  [veritas] status=${order.status}   \r`);
        },
      },
    });
  } catch (e: unknown) {
    const msg = e instanceof Error ? e.message : String(e);
    console.error(`  [veritas] hire failed: ${msg}`);
    const { score, answer } = buildFinalAnswer(query.draftAnswer, null);
    return {
      topic: query.topic,
      draftAnswer: query.draftAnswer,
      verificationReport: null,
      trustScore: score,
      finalAnswer: answer,
    };
  }

  const report = hireResult.report;
  const { score, answer } = buildFinalAnswer(query.draftAnswer, report);

  return {
    topic: query.topic,
    draftAnswer: query.draftAnswer,
    verificationReport: report,
    trustScore: score,
    finalAnswer: answer,
  };
}

/** Print a concise research result to stdout. */
function printResult(result: ResearchResult): void {
  console.log(`\n${"=".repeat(60)}`);
  console.log(`Topic      : ${result.topic}`);
  console.log(`Trust Score: ${(result.trustScore * 100).toFixed(1)}%`);
  console.log(`\nFinal Answer:\n${result.finalAnswer}`);
  console.log("=".repeat(60));
}

/** Sample research queries demonstrating the agent workflow. */
const DEMO_QUERIES: ResearchQuery[] = [
  {
    topic: "Moon landing",
    draftAnswer:
      "NASA's Apollo 11 mission successfully landed humans on the Moon on July 20, 1969. Neil Armstrong was the first person to walk on the lunar surface.",
  },
  {
    topic: "Population claim",
    draftAnswer:
      "As of 2024, the global human population exceeds 10 billion people, making Earth increasingly resource-constrained.",
  },
];

async function main(): Promise<void> {
  const cfg = loadAgentConfig();
  const client = new VeritasClient({
    apiKey: cfg.veritasApiKey,
    baseUrl: cfg.veritasApiBase,
  });

  console.log("=== A2A Research Agent with Veritas Fact-Checking ===");
  console.log(`Veritas API : ${cfg.veritasApiBase}`);
  console.log(`Service ID  : ${cfg.veritasServiceId}`);
  console.log(`Queries     : ${DEMO_QUERIES.length}`);

  for (const query of DEMO_QUERIES) {
    const result = await factCheckDraft(client, cfg, query);
    printResult(result);
  }

  console.log("\nResearch agent run complete.");
}

main().catch((err: unknown) => {
  console.error("a2a-research-agent failed:", err instanceof Error ? err.message : String(err));
  process.exit(1);
});
